# Generated by Django 4.2.5 on 2023-09-18 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_alter_transaction_amount_point'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Point',
        ),
    ]
